import 'package:appwrite/appwrite.dart';
import 'package:hackaton_v1/models/recipe_model.dart';

List<RecipeModel> mock = [
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Spicy Chicken Stir-Fry",
    description:
        "This spicy chicken stir-fry is packed with flavor and comes together quickly for a satisfying meal.",
    illustrationPic: "64890dd6c1af7ca29289",
    ingredients: [
      "2 boneless, skinless chicken breasts",
      "2 tablespoons soy sauce",
      "1 tablespoon Sriracha sauce",
      "2 cloves garlic, minced",
      "1 red bell pepper, sliced",
    ],
    cookingTime: "30 min",
    cookingSteps: [
      "In a bowl, combine the soy sauce, Sriracha sauce, and minced garlic. Slice the chicken into thin strips and add them to the bowl. Marinate for 10 minutes.",
      "Heat the vegetable oil in a large skillet over medium-high heat. Add the marinated chicken and cook until browned and cooked through, about 5-6 minutes.",
      "Add the sliced bell pepper and onion to the skillet. Stir-fry for an additional 3-4 minutes until the vegetables are tender-crisp.",
      "Season with salt and pepper to taste. Serve hot with steamed rice or noodles.",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
    ],
    likes: 100,
    views: 50,
    queryableString:
        "Spicy Chicken Stir-Fry 2 boneless, skinless chicken breasts 2 tablespoons soy sauce 1 tablespoon Sriracha sauce 2 cloves garlic, minced 1 red bell pepper, sliced",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Classic Margherita Pizza",
    description:
        "Enjoy the simplicity and flavors of a classic Margherita pizza with fresh basil and melty mozzarella cheese.",
    illustrationPic: "64890dd6c1af7ca29289",
    ingredients: [
      "1 pizza dough",
      "1/2 cup pizza sauce",
      "2 cups shredded mozzarella cheese",
      "Fresh basil leaves",
      "Extra-virgin olive oil",
      "Salt and pepper to taste",
    ],
    cookingTime: "20 min",
    cookingSteps: [
      "Preheat the oven to the highest temperature setting (usually around 500°F or 260°C).",
      "Roll out the pizza dough on a lightly floured surface into your desired shape.",
      "Transfer the rolled-out dough onto a pizza stone or baking sheet.",
      "Spread the pizza sauce evenly over the dough, leaving a small border around the edges.",
      "Sprinkle the shredded mozzarella cheese over the sauce.",
      "Place fresh basil leaves on top of the cheese.",
      "Drizzle olive oil over the pizza. Season with salt and pepper.",
      "Bake in the preheated oven for about 10-12 minutes or until the crust is golden and the cheese is melted and bubbly.",
      "Remove from the oven and let it cool slightly before slicing. Enjoy!",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
    ],
    likes: 150,
    views: 80,
    queryableString:
        "Classic Margherita Pizza 1 pizza dough 1/2 cup pizza sauce 2 cups shredded mozzarella cheese Fresh basil leaves Extra-virgin olive oil Salt and pepper to taste",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Creamy Garlic Parmesan Pasta",
    description:
        "Indulge in a creamy and flavorful garlic Parmesan pasta dish that's quick and easy to prepare.",
    illustrationPic: "64890dd6c1af7ca29289",
    ingredients: [
      "8 oz fettuccine or any pasta of your choice",
      "2 tablespoons butter",
      "4 cloves garlic, minced",
      "1 cup heavy cream",
      "1 cup grated Parmesan cheese",
      "Salt and pepper to taste",
      "Fresh parsley, chopped (for garnish)",
    ],
    cookingTime: "25 min",
    cookingSteps: [
      "Cook the pasta according to package instructions until al dente. Drain and set aside.",
      "In a large skillet, melt the butter over medium heat. Add the minced garlic and sauté until fragrant, about 1 minute.",
      "Pour in the heavy cream and bring it to a simmer. Let it cook for 2-3 minutes until slightly thickened.",
      "Add the grated Parmesan cheese to the skillet and stir until melted and smooth. Season with salt and pepper to taste.",
      "Add the cooked pasta to the skillet and toss until well coated with the sauce.",
      "Garnish with fresh parsley and serve hot.",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
    ],
    likes: 120,
    views: 70,
    queryableString:
        "Creamy Garlic Parmesan Pasta 8 oz fettuccine or any pasta of your choice 2 tablespoons butter 4 cloves garlic, minced 1 cup heavy cream 1 cup grated Parmesan cheese Salt and pepper to taste Fresh parsley, chopped",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Baked Lemon Herb Salmon",
    description:
        "Enjoy a healthy and flavorful baked salmon dish infused with tangy lemon and aromatic herbs.",
    illustrationPic: "64890dd6c1af7ca29289",
    ingredients: [
      "2 salmon fillets",
      "1 lemon, sliced",
      "2 tablespoons olive oil",
      "2 cloves garlic, minced",
      "1 teaspoon dried thyme",
      "Salt and pepper to taste",
    ],
    cookingTime: "35 min",
    cookingSteps: [
      "Preheat the oven to 400°F (200°C). Line a baking sheet with parchment paper.",
      "Place the salmon fillets on the prepared baking sheet. Drizzle with olive oil and squeeze fresh lemon juice over the fillets.",
      "Sprinkle minced garlic, dried thyme, salt, and pepper over the salmon.",
      "Place lemon slices on top of the fillets for extra flavor and presentation.",
      "Bake in the preheated oven for about 20-25 minutes or until the salmon is cooked through and flakes easily with a fork.",
      "Remove from the oven and let it rest for a few minutes before serving. Enjoy!",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "",
      ""
    ],
    likes: 90,
    views: 60,
    queryableString:
        "Baked Lemon Herb Salmon 2 salmon fillets 1 lemon, sliced 2 tablespoons olive oil 2 cloves garlic, minced 1 teaspoon dried thyme Salt and pepper to taste",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Mushroom Risotto",
    description:
        "Indulge in a creamy and comforting mushroom risotto that's perfect as a main dish or side.",
    illustrationPic: "64890dd6c1af7ca29289",
    ingredients: [
      "1 cup Arborio rice",
      "4 cups vegetable broth",
      "1 cup mushrooms, sliced",
      "1 onion, chopped",
      "3 cloves garlic, minced",
      "1/2 cup grated Parmesan cheese",
      "2 tablespoons butter",
      "2 tablespoons olive oil",
      "Salt and pepper to taste",
      "Fresh parsley, chopped (for garnish)",
    ],
    cookingTime: "45 min",
    cookingSteps: [
      "In a large saucepan, heat the olive oil and butter over medium heat. Add the chopped onion and minced garlic. Sauté until the onion is translucent and the garlic is fragrant.",
      "Add the sliced mushrooms to the saucepan and cook until they release their moisture and turn golden brown.",
      "Add the Arborio rice to the saucepan and stir to coat it with the oil and butter mixture. Cook for 1-2 minutes to toast the rice slightly.",
      "Slowly add the vegetable broth to the saucepan, about 1 cup at a time, stirring frequently. Allow each addition of broth to be absorbed before adding more.",
      "Continue adding the broth and stirring until the rice is creamy and al dente, about 25-30 minutes.",
      "Stir in the grated Parmesan cheese until melted and well incorporated. Season with salt and pepper to taste.",
      "Garnish with fresh parsley and serve hot.",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      ""
    ],
    likes: 80,
    views: 40,
    queryableString:
        "Mushroom Risotto 1 cup Arborio rice 4 cups vegetable broth 1 cup mushrooms, sliced 1 onion, chopped 3 cloves garlic, minced 1/2 cup grated Parmesan cheese 2 tablespoons butter 2 tablespoons olive oil Salt and pepper to taste Fresh parsley, chopped",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Homemade Chicken Noodle Soup",
    description:
        "Warm up with a comforting bowl of homemade chicken noodle soup, perfect for chilly days or when you're feeling under the weather.",
    illustrationPic: "64890dd6c1af7ca29289",
    ingredients: [
      "2 boneless, skinless chicken breasts",
      "8 cups chicken broth",
      "1 onion, chopped",
      "3 carrots, sliced",
      "3 celery stalks, sliced",
      "3 cloves garlic, minced",
      "2 bay leaves",
      "1 teaspoon dried thyme",
      "Salt and pepper to taste",
      "8 oz egg noodles",
      "Fresh parsley, chopped (for garnish)",
    ],
    cookingTime: "1 hr 30 min",
    cookingSteps: [
      "In a large pot, bring the chicken broth to a boil. Add the whole chicken breasts, chopped onion, sliced carrots, sliced celery, minced garlic, bay leaves, dried thyme, salt, and pepper.",
      "Reduce the heat to low and let the soup simmer for about 30-40 minutes until the chicken is cooked through and tender.",
      "Remove the chicken breasts from the pot and shred them using two forks. Set the shredded chicken aside.",
      "Return the shredded chicken to the pot. Add the egg noodles and cook according to package instructions until al dente.",
      "Taste the soup and adjust the seasoning with salt and pepper if needed.",
      "Garnish with fresh parsley and serve hot. Enjoy!",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
    ],
    likes: 120,
    views: 60,
    queryableString:
        "Homemade Chicken Noodle Soup 2 boneless, skinless chicken breasts 8 cups chicken broth 1 onion, chopped 3 carrots, sliced 3 celery stalks, sliced 3 cloves garlic, minced 2 bay leaves 1 teaspoon dried thyme Salt and pepper to taste 8 oz egg noodles Fresh parsley, chopped",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Beef Stir-Fry with Vegetables",
    description:
        "Savor the flavors of a delicious beef stir-fry loaded with colorful vegetables and a savory sauce.",
    illustrationPic: "64890dd6c1af7ca29289",
    ingredients: [
      "1 lb beef sirloin, thinly sliced",
      "2 tablespoons soy sauce",
      "2 tablespoons oyster sauce",
      "1 tablespoon hoisin sauce",
      "2 tablespoons vegetable oil",
      "3 cloves garlic, minced",
      "1 red bell pepper, sliced",
      "1 yellow bell pepper, sliced",
      "1 onion, sliced",
      "2 cups broccoli florets",
      "Salt and pepper to taste",
      "Cooked rice or noodles, for serving",
      "Green onions, chopped (for garnish)",
    ],
    cookingTime: "35 min",
    cookingSteps: [
      "In a bowl, combine the soy sauce, oyster sauce, and hoisin sauce. Add the sliced beef and marinate for 15 minutes.",
      "Heat the vegetable oil in a large skillet or wok over high heat. Add the minced garlic and stir-fry for a few seconds until fragrant.",
      "Add the marinated beef to the skillet and stir-fry until browned and cooked to your desired doneness.",
      "Push the beef to one side of the skillet and add the sliced bell peppers, onion, and broccoli florets. Stir-fry for 2-3 minutes until the vegetables are crisp-tender.",
      "Season with salt and pepper to taste. Toss everything together to combine.",
      "Serve the beef stir-fry over cooked rice or noodles. Garnish with chopped green onions. Enjoy!",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      ""
    ],
    likes: 100,
    views: 50,
    queryableString:
        "Beef Stir-Fry with Vegetables 1 lb beef sirloin, thinly sliced 2 tablespoons soy sauce 2 tablespoons oyster sauce 1 tablespoon hoisin sauce 2 tablespoons vegetable oil 3 cloves garlic, minced 1 red bell pepper, sliced 1 yellow bell pepper, sliced 1 onion, sliced 2 cups broccoli florets Salt and pepper to taste Cooked rice or noodles, Green onions, chopped",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Caprese Salad",
    description:
        "Enjoy the freshness of a classic Caprese salad with ripe tomatoes, fresh mozzarella, and fragrant basil leaves.",
    illustrationPic: "64890dd6c1af7ca29289",
    ingredients: [
      "2 large tomatoes, sliced",
      "8 oz fresh mozzarella cheese, sliced",
      "Fresh basil leaves",
      "Extra-virgin olive oil",
      "Balsamic glaze",
      "Salt and pepper to taste",
    ],
    cookingTime: "10 min",
    cookingSteps: [
      "Arrange the tomato slices and mozzarella slices on a serving platter, alternating between the two.",
      "Tuck fresh basil leaves in between the tomato and mozzarella slices.",
      "Drizzle extra-virgin olive oil over the salad.",
      "Drizzle balsamic glaze over the salad.",
      "Season with salt and pepper to taste.",
      "Serve immediately and enjoy the refreshing Caprese salad.",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      ""
    ],
    likes: 80,
    views: 40,
    queryableString:
        "Caprese Salad 2 large tomatoes, sliced 8 oz fresh mozzarella cheese, sliced Fresh basil leaves Extra-virgin olive oil Balsamic glaze Salt and pepper to taste",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Pasta Carbonara",
    description:
        "Indulge in a classic Italian pasta carbonara dish with creamy egg sauce, crispy bacon, and Parmesan cheese.",
    illustrationPic: "64890dd6c1af7ca29289",
    ingredients: [
      "8 oz spaghetti or any pasta of your choice",
      "4 slices bacon, chopped",
      "3 cloves garlic, minced",
      "2 large eggs",
      "1/2 cup grated Parmesan cheese",
      "Salt and pepper to taste",
      "Fresh parsley, chopped (for garnish)",
    ],
    cookingTime: "25 min",
    cookingSteps: [
      "Cook the pasta according to package instructions until al dente. Drain and set aside.",
      "In a skillet, cook the chopped bacon over medium heat until crispy. Remove the bacon from the skillet and set it aside on a paper towel-lined plate.",
      "In the same skillet, sauté the minced garlic in the bacon fat until fragrant.",
      "In a bowl, whisk together the eggs, grated Parmesan cheese, salt, and pepper.",
      "Pour the egg mixture into the skillet with the sautéed garlic. Stir quickly to combine and cook for about 1 minute until the sauce thickens slightly.",
      "Add the cooked pasta to the skillet and toss until well coated with the sauce.",
      "Stir in the crispy bacon. Taste and adjust the seasoning if needed.",
      "Garnish with fresh parsley and serve hot.",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
    ],
    likes: 150,
    views: 80,
    queryableString:
        "Pasta Carbonara 8 oz spaghetti or any pasta of your choice 4 slices bacon, chopped 3 cloves garlic, minced 2 large eggs 1/2 cup grated Parmesan cheese Salt and pepper to taste Fresh parsley, chopped",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Greek Salad",
    description:
        "Enjoy the flavors of the Mediterranean with this refreshing Greek salad loaded with crisp vegetables, tangy feta cheese, and a zesty dressing.",
    illustrationPic: "64890dd6c1af7ca29289",
    ingredients: [
      "2 large cucumbers, diced",
      "4 ripe tomatoes, diced",
      "1 red onion, thinly sliced",
      "1 green bell pepper, diced",
      "1/2 cup Kalamata olives",
      "4 oz feta cheese, crumbled",
      "Fresh oregano leaves",
      "Extra-virgin olive oil",
      "Red wine vinegar",
      "Salt and pepper to taste",
    ],
    cookingTime: "15 min",
    cookingSteps: [
      "In a large salad bowl, combine the diced cucumbers, tomatoes, red onion, and green bell pepper.",
      "Add the Kalamata olives and crumbled feta cheese to the bowl.",
      "Sprinkle fresh oregano leaves over the salad.",
      "Drizzle extra-virgin olive oil and red wine vinegar over the salad.",
      "Season with salt and pepper to taste.",
      "Toss everything together until well combined.",
      "Serve the Greek salad as a refreshing appetizer or side dish.",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
    ],
    likes: 90,
    views: 50,
    queryableString:
        "Greek Salad 2 large cucumbers, diced 4 ripe tomatoes, diced 1 red onion, thinly sliced 1 green bell pepper, diced 1/2 cup Kalamata olives 4 oz feta cheese, crumbled Fresh oregano leaves Extra-virgin olive oil Red wine vinegar Salt and pepper to taste",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Spinach and Feta Stuffed Chicken Breast",
    description:
        "Elevate your chicken dinner with this delicious spinach and feta stuffed chicken breast that's juicy, flavorful, and oh-so-satisfying.",
    illustrationPic: "64890dd6c1af7ca29289",
    ingredients: [
      "4 boneless, skinless chicken breasts",
      "2 cups fresh spinach",
      "1/2 cup crumbled feta cheese",
      "2 cloves garlic, minced",
      "1 teaspoon dried oregano",
      "Salt and pepper to taste",
      "2 tablespoons olive oil",
    ],
    cookingTime: "40 min",
    cookingSteps: [
      "Preheat the oven to 375°F (190°C).",
      "In a skillet, heat the olive oil over medium heat. Add the minced garlic and sauté for a few seconds until fragrant.",
      "Add the fresh spinach to the skillet and cook until wilted. Remove from heat.",
      "Using a sharp knife, cut a pocket into each chicken breast. Be careful not to cut all the way through.",
      "In a bowl, combine the wilted spinach, crumbled feta cheese, dried oregano, salt, and pepper.",
      "Stuff each chicken breast with the spinach and feta mixture, pressing the edges to seal.",
      "Place the stuffed chicken breasts on a baking sheet and bake in the preheated oven for 25-30 minutes until the chicken is cooked through.",
      "Serve the spinach and feta stuffed chicken breast with your favorite side dishes. Enjoy!",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      ""
    ],
    likes: 110,
    views: 60,
    queryableString:
        "Spinach and Feta Stuffed Chicken Breast 4 boneless, skinless chicken breasts 2 cups fresh spinach 1/2 cup crumbled feta cheese 2 cloves garlic, minced 1 teaspoon dried oregano Salt and pepper to taste 2 tablespoons olive oil",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Mediterranean Quinoa Salad",
    description:
        "Enjoy a nutritious and flavorful Mediterranean quinoa salad packed with fresh vegetables, tangy olives, and a zesty lemon dressing.",
    illustrationPic: "64890dd6c1af7ca29289",
    ingredients: [
      "1 cup quinoa, cooked",
      "1 cucumber, diced",
      "1 red bell pepper, diced",
      "1/2 red onion, finely chopped",
      "1/2 cup Kalamata olives, pitted and halved",
      "1/4 cup fresh parsley, chopped",
      "1/4 cup fresh mint leaves, chopped",
      "Juice of 1 lemon",
      "2 tablespoons extra-virgin olive oil",
      "Salt and pepper to taste",
    ],
    cookingTime: "20 min",
    cookingSteps: [
      "In a large bowl, combine the cooked quinoa, diced cucumber, diced red bell pepper, finely chopped red onion, Kalamata olives, chopped parsley, and chopped mint leaves.",
      "In a small bowl, whisk together the lemon juice, extra-virgin olive oil, salt, and pepper to make the dressing.",
      "Pour the dressing over the quinoa salad and toss until well coated.",
      "Adjust the seasoning with salt and pepper if needed.",
      "Chill the Mediterranean quinoa salad in the refrigerator for at least 30 minutes to allow the flavors to meld together.",
      "Serve the salad as a light and refreshing meal or side dish.",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      ""
    ],
    likes: 70,
    views: 40,
    queryableString:
        "Mediterranean Quinoa Salad 1 cup quinoa, cooked 1 cucumber, diced 1 red bell pepper, diced 1/2 red onion, finely chopped 1/2 cup Kalamata olives, pitted and halved 1/4 cup fresh parsley, chopped 1/4 cup fresh mint leaves, chopped Juice of 1 lemon 2 tablespoons extra-virgin olive oil Salt and pepper to taste",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Honey Mustard Baked Salmon",
    description:
        "Enjoy a flavorful and healthy meal with this honey mustard baked salmon that's tender, flaky, and glazed with a sweet and tangy sauce.",
    illustrationPic: "64890dd6c1af7ca29289",
    ingredients: [
      "4 salmon fillets",
      "2 tablespoons Dijon mustard",
      "2 tablespoons honey",
      "1 tablespoon soy sauce",
      "1 tablespoon lemon juice",
      "2 cloves garlic, minced",
      "Salt and pepper to taste",
      "Fresh dill, chopped (for garnish)",
    ],
    cookingTime: "20 min",
    cookingSteps: [
      "Preheat the oven to 375°F (190°C).",
      "In a small bowl, whisk together the Dijon mustard, honey, soy sauce, lemon juice, minced garlic, salt, and pepper to make the honey mustard glaze.",
      "Place the salmon fillets on a baking sheet lined with parchment paper.",
      "Brush the honey mustard glaze over the salmon fillets, ensuring they are fully coated.",
      "Bake in the preheated oven for 12-15 minutes until the salmon is cooked through and flakes easily with a fork.",
      "Garnish with fresh dill and serve hot.",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      ""
    ],
    likes: 120,
    views: 70,
    queryableString:
        "Honey Mustard Baked Salmon 4 salmon fillets 2 tablespoons Dijon mustard 2 tablespoons honey 1 tablespoon soy sauce 1 tablespoon lemon juice 2 cloves garlic, minced Salt and pepper to taste Fresh dill, chopped",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Vegetable Curry",
    description:
        "Delight your taste buds with this flavorful vegetable curry made with a medley of colorful vegetables, aromatic spices, and creamy coconut milk.",
    illustrationPic: "64890db908b8f19b4dec",
    ingredients: [
      "1 tablespoon vegetable oil",
      "1 onion, diced",
      "2 cloves garlic, minced",
      "1 tablespoon curry powder",
      "1 teaspoon ground cumin",
      "1 teaspoon ground coriander",
      "1/2 teaspoon turmeric",
      "1/4 teaspoon cayenne pepper (optional)",
      "1 can (14 oz) coconut milk",
      "2 cups mixed vegetables (such as carrots, bell peppers, peas, and cauliflower)",
      "Salt and pepper to taste",
      "Fresh cilantro, chopped (for garnish)",
    ],
    cookingTime: "30 min",
    cookingSteps: [
      "In a large skillet or wok, heat the vegetable oil over medium heat.",
      "Add the diced onion and minced garlic to the skillet and sauté until softened and fragrant.",
      "Add the curry powder, ground cumin, ground coriander, turmeric, and cayenne pepper (if using) to the skillet. Stir well to coat the onions and garlic with the spices.",
      "Pour in the coconut milk and stir to combine with the spices.",
      "Add the mixed vegetables to the skillet and simmer for 15-20 minutes until the vegetables are tender and cooked through.",
      "Season with salt and pepper to taste.",
      "Garnish with chopped fresh cilantro and serve the vegetable curry over steamed rice or with naan bread.",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      ""
    ],
    likes: 80,
    views: 50,
    queryableString:
        "Vegetable Curry 1 tablespoon vegetable oil 1 onion, diced 2 cloves garlic, minced 1 tablespoon curry powder 1 teaspoon ground cumin 1 teaspoon ground coriander 1/2 teaspoon turmeric 1/4 teaspoon cayenne pepper (optional) 1 can (14 oz) coconut milk 2 cups mixed vegetables (such as carrots, bell peppers, peas, and cauliflower) Salt and pepper to taste Fresh cilantro, chopped",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Caprese Skewers",
    description:
        "Indulge in these delightful caprese skewers featuring fresh mozzarella, juicy cherry tomatoes, fragrant basil leaves, and a drizzle of balsamic glaze.",
    illustrationPic: "64890db908b8f19b4dec",
    ingredients: [
      "8 oz fresh mozzarella balls",
      "1 pint cherry tomatoes",
      "Fresh basil leaves",
      "Balsamic glaze",
      "Extra-virgin olive oil",
      "Salt and pepper to taste",
    ],
    cookingTime: "15 min",
    cookingSteps: [
      "Thread a fresh mozzarella ball, a cherry tomato, and a basil leaf onto a skewer. Repeat for the remaining ingredients.",
      "Arrange the caprese skewers on a serving platter.",
      "Drizzle balsamic glaze and extra-virgin olive oil over the skewers.",
      "Season with salt and pepper to taste.",
      "Serve the caprese skewers as a delicious appetizer or party snack.",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      ""
    ],
    likes: 90,
    views: 60,
    queryableString:
        "Caprese Skewers 8 oz fresh mozzarella balls 1 pint cherry tomatoes Fresh basil leaves Balsamic glaze Extra-virgin olive oil Salt and pepper to taste",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Teriyaki Chicken Stir-Fry",
    description:
        "Whip up a quick and delicious teriyaki chicken stir-fry that's packed with tender chicken, crisp vegetables, and a flavorful homemade teriyaki sauce.",
    illustrationPic: "64890db908b8f19b4dec",
    ingredients: [
      "1 lb boneless, skinless chicken breasts, sliced",
      "2 tablespoons vegetable oil",
      "2 cloves garlic, minced",
      "1 bell pepper, sliced",
      "1 cup broccoli florets",
      "1 carrot, sliced",
      "1/2 cup snap peas",
      "1/4 cup soy sauce",
      "2 tablespoons honey",
      "1 tablespoon rice vinegar",
      "1 tablespoon cornstarch",
      "1/4 teaspoon red pepper flakes (optional)",
      "Sesame seeds (for garnish)",
      "Cooked rice (for serving)",
    ],
    cookingTime: "25 min",
    cookingSteps: [
      "In a small bowl, whisk together the soy sauce, honey, rice vinegar, cornstarch, and red pepper flakes (if using) to make the teriyaki sauce.",
      "In a large skillet or wok, heat the vegetable oil over medium-high heat.",
      "Add the minced garlic to the skillet and sauté for a few seconds until fragrant.",
      "Add the sliced chicken breasts to the skillet and cook until browned and cooked through.",
      "Remove the cooked chicken from the skillet and set aside.",
      "In the same skillet, add the bell pepper, broccoli florets, sliced carrot, and snap peas. Stir-fry until the vegetables are crisp-tender.",
      "Return the cooked chicken to the skillet and pour the teriyaki sauce over the chicken and vegetables.",
      "Cook for a few more minutes until the sauce thickens and coats the chicken and vegetables.",
      "Garnish with sesame seeds and serve the teriyaki chicken stir-fry over cooked rice.",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      ""
    ],
    likes: 100,
    views: 70,
    queryableString:
        "Teriyaki Chicken Stir-Fry 1 lb boneless, skinless chicken breasts, sliced 2 tablespoons vegetable oil 2 cloves garlic, minced 1 bell pepper, sliced 1 cup broccoli florets 1 carrot, sliced 1/2 cup snap peas 1/4 cup soy sauce 2 tablespoons honey 1 tablespoon rice vinegar 1 tablespoon cornstarch 1/4 teaspoon red pepper flakes (optional) Sesame seeds Cooked rice",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Creamy Garlic Mashed Potatoes",
    description:
        "Indulge in these smooth and creamy garlic mashed potatoes that make the perfect side dish for any meal.",
    illustrationPic: "64890db908b8f19b4dec",
    ingredients: [
      "2 lbs Yukon gold potatoes, peeled and quartered",
      "4 cloves garlic, minced",
      "1/2 cup unsalted butter, melted",
      "1/2 cup milk or heavy cream",
      "Salt and pepper to taste",
      "Chopped chives (for garnish)",
    ],
    cookingTime: "30 min",
    cookingSteps: [
      "Place the peeled and quartered potatoes in a large pot and cover with cold water.",
      "Add a pinch of salt to the water and bring to a boil over high heat.",
      "Reduce the heat to medium and simmer for 15-20 minutes until the potatoes are tender when pierced with a fork.",
      "While the potatoes are cooking, melt the butter in a small saucepan over low heat. Add the minced garlic to the melted butter and cook for a few minutes until fragrant.",
      "Drain the cooked potatoes and return them to the pot.",
      "Pour the melted butter and garlic mixture over the potatoes.",
      "Using a potato masher or a fork, mash the potatoes until smooth and creamy.",
      "Gradually add the milk or heavy cream while mashing until the desired consistency is reached.",
      "Season with salt and pepper to taste.",
      "Garnish with chopped chives and serve the creamy garlic mashed potatoes hot.",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
    ],
    likes: 80,
    views: 60,
    queryableString:
        "Creamy Garlic Mashed Potatoes 2 lbs Yukon gold potatoes, peeled and quartered 4 cloves garlic, minced 1/2 cup unsalted butter, melted 1/2 cup milk or heavy cream Salt and pepper to taste Chopped chives",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Shrimp Scampi",
    description:
        "Savor the flavors of this classic shrimp scampi dish featuring succulent shrimp cooked in a buttery garlic and lemon sauce.",
    illustrationPic: "64890db908b8f19b4dec",
    ingredients: [
      "1 lb shrimp, peeled and deveined",
      "4 tablespoons unsalted butter",
      "4 cloves garlic, minced",
      "1/2 cup white wine",
      "Juice of 1 lemon",
      "Zest of 1 lemon",
      "Salt and pepper to taste",
      "Fresh parsley, chopped (for garnish)",
      "Cooked pasta (optional, for serving)",
    ],
    cookingTime: "15 min",
    cookingSteps: [
      "In a large skillet, melt the butter over medium heat.",
      "Add the minced garlic to the skillet and sauté for a minute until fragrant.",
      "Add the shrimp to the skillet and cook for 2-3 minutes until pink and cooked through.",
      "Remove the cooked shrimp from the skillet and set aside.",
      "Pour the white wine into the skillet and bring to a simmer. Cook for a few minutes until the wine has reduced slightly.",
      "Add the lemon juice and lemon zest to the skillet. Stir well to combine.",
      "Season the sauce with salt and pepper to taste.",
      "Return the cooked shrimp to the skillet and toss to coat with the sauce.",
      "Garnish with chopped fresh parsley and serve the shrimp scampi as is or over cooked pasta.",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      ""
    ],
    likes: 110,
    views: 80,
    queryableString:
        "Shrimp Scampi 1 lb shrimp, peeled and deveined 4 tablespoons unsalted butter 4 cloves garlic, minced 1/2 cup white wine Juice of 1 lemon Zest of 1 lemon Salt and pepper to taste Fresh parsley Cooked pasta",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Homemade Pizza",
    description:
        "Create your own delicious homemade pizza with your favorite toppings and enjoy a slice of cheesy goodness.",
    illustrationPic: "64890db908b8f19b4dec",
    ingredients: [
      "Pizza dough (store-bought or homemade)",
      "Pizza sauce",
      "Shredded mozzarella cheese",
      "Assorted toppings (such as pepperoni, sliced bell peppers, sliced onions, mushrooms, and olives)",
      "Dried oregano",
      "Red pepper flakes (optional)",
      "Fresh basil leaves (for garnish)",
    ],
    cookingTime: "25 min",
    cookingSteps: [
      "Preheat the oven to the temperature recommended on the pizza dough packaging or your homemade pizza dough recipe.",
      "Roll out the pizza dough on a floured surface to your desired thickness.",
      "Transfer the rolled-out dough to a baking sheet or pizza stone.",
      "Spread a layer of pizza sauce over the dough, leaving a small border around the edges.",
      "Sprinkle shredded mozzarella cheese evenly over the sauce.",
      "Add your preferred toppings, such as pepperoni, sliced bell peppers, sliced onions, mushrooms, and olives.",
      "Sprinkle dried oregano and red pepper flakes (if desired) over the toppings.",
      "Bake in the preheated oven for the time specified on the pizza dough packaging or until the crust is golden and the cheese is bubbly and lightly browned.",
      "Remove the pizza from the oven and let it cool slightly.",
      "Garnish with fresh basil leaves, slice, and serve hot.",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
    ],
    likes: 120,
    views: 90,
    queryableString:
        "Homemade Pizza Pizza dough Pizza sauce Shredded mozzarella cheese Assorted toppings Dried oregano Red pepper flakes Fresh basil leaves",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Chicken Fajitas",
    description:
        "Enjoy the sizzling flavors of chicken fajitas packed with tender marinated chicken, sautéed bell peppers, onions, and a medley of spices.",
    illustrationPic: "64890db908b8f19b4dec",
    ingredients: [
      "1 lb chicken breasts, sliced",
      "1 bell pepper, sliced",
      "1 onion, sliced",
      "2 tablespoons vegetable oil",
      "Juice of 1 lime",
      "1 tablespoon chili powder",
      "1 teaspoon ground cumin",
      "1 teaspoon paprika",
      "1/2 teaspoon garlic powder",
      "1/2 teaspoon onion powder",
      "1/4 teaspoon cayenne pepper (optional)",
      "Salt and pepper to taste",
      "Tortillas",
      "Optional toppings: salsa, guacamole, sour cream, shredded cheese",
    ],
    cookingTime: "20 min",
    cookingSteps: [
      "In a bowl, combine the sliced chicken, lime juice, chili powder, ground cumin, paprika, garlic powder, onion powder, cayenne pepper (if using), salt, and pepper. Toss to coat the chicken with the marinade.",
      "Heat the vegetable oil in a skillet over medium-high heat.",
      "Add the marinated chicken to the skillet and cook until browned and cooked through.",
      "Remove the cooked chicken from the skillet and set aside.",
      "In the same skillet, add the sliced bell pepper and onion. Sauté until the vegetables are tender and slightly charred.",
      "Return the cooked chicken to the skillet and toss with the sautéed bell pepper and onion.",
      "Warm the tortillas according to the package instructions.",
      "Serve the chicken fajitas in warm tortillas with your choice of toppings, such as salsa, guacamole, sour cream, and shredded cheese.",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
    ],
    likes: 130,
    views: 100,
    queryableString:
        "Chicken Fajitas 1 lb chicken breasts, sliced 1 bell pepper, sliced 1 onion, sliced 2 tablespoons vegetable oil Juice of 1 lime 1 tablespoon chili powder 1 teaspoon ground cumin 1 teaspoon paprika 1/2 teaspoon garlic powder 1/2 teaspoon onion powder 1/4 teaspoon cayenne pepper Salt and pepper Tortillas Optional toppings",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Stuffed Bell Peppers",
    description:
        "Delight in these colorful and delicious stuffed bell peppers filled with a flavorful mixture of ground beef, rice, vegetables, and melted cheese.",
    illustrationPic: "64890db908b8f19b4dec",
    ingredients: [
      "4 bell peppers (any color), tops removed and seeds removed",
      "1 lb ground beef",
      "1 onion, diced",
      "2 cloves garlic, minced",
      "1 cup cooked rice",
      "1 cup diced tomatoes",
      "1 cup shredded cheese (such as cheddar or mozzarella)",
      "1 tablespoon tomato paste",
      "1 teaspoon dried oregano",
      "1 teaspoon dried basil",
      "Salt and pepper to taste",
      "Fresh parsley, chopped (for garnish)",
    ],
    cookingTime: "40 min",
    cookingSteps: [
      "Preheat the oven to 375°F (190°C).",
      "Place the bell peppers in a baking dish, standing upright.",
      "In a skillet, brown the ground beef over medium heat. Drain any excess fat.",
      "Add the diced onion and minced garlic to the skillet with the ground beef. Sauté until the onion is tender.",
      "Stir in the cooked rice, diced tomatoes, tomato paste, dried oregano, dried basil, salt, and pepper. Cook for a few minutes until well combined.",
      "Spoon the beef and rice mixture into the hollowed-out bell peppers, filling them to the top.",
      "Sprinkle shredded cheese over the stuffed bell peppers.",
      "Cover the baking dish with foil and bake in the preheated oven for 25 minutes.",
      "Remove the foil and bake for an additional 10-15 minutes until the bell peppers are tender and the cheese is melted and lightly browned.",
      "Garnish with chopped fresh parsley and serve the stuffed bell peppers hot.",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
    ],
    likes: 140,
    views: 110,
    queryableString:
        "Stuffed Bell Peppers 4 bell peppers 1 lb ground beef 1 onion, diced 2 cloves garlic, minced 1 cup cooked rice 1 cup diced tomatoes 1 cup shredded cheese 1 tablespoon tomato paste 1 teaspoon dried oregano 1 teaspoon dried basil Salt and pepper Fresh parsley",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Beef Stir-Fry",
    description:
        "Enjoy a quick and flavorful beef stir-fry loaded with tender beef slices, crisp vegetables, and a savory sauce.",
    illustrationPic: "64890db908b8f19b4dec",
    ingredients: [
      "1 lb beef sirloin, thinly sliced",
      "2 tablespoons soy sauce",
      "1 tablespoon oyster sauce",
      "1 tablespoon cornstarch",
      "1 tablespoon vegetable oil",
      "2 cloves garlic, minced",
      "1 bell pepper, sliced",
      "1 onion, sliced",
      "1 cup broccoli florets",
      "1/2 cup sliced mushrooms",
      "1/2 cup beef broth",
      "Salt and pepper to taste",
      "Cooked rice or noodles (for serving)",
    ],
    cookingTime: "20 min",
    cookingSteps: [
      "In a bowl, combine the sliced beef, soy sauce, oyster sauce, and cornstarch. Toss to coat the beef with the marinade.",
      "Heat the vegetable oil in a large skillet or wok over high heat.",
      "Add the minced garlic to the skillet and stir-fry for a few seconds until fragrant.",
      "Add the marinated beef to the skillet and stir-fry for 2-3 minutes until browned and cooked to your desired level of doneness. Remove the beef from the skillet and set aside.",
      "In the same skillet, add the bell pepper, onion, broccoli florets, and sliced mushrooms. Stir-fry for 3-4 minutes until the vegetables are crisp-tender.",
      "Pour the beef broth into the skillet and bring to a simmer. Cook for a minute to heat the broth.",
      "Return the cooked beef to the skillet and toss with the vegetables.",
      "Season with salt and pepper to taste.",
      "Serve the beef stir-fry over cooked rice or noodles.",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      ""
    ],
    likes: 150,
    views: 120,
    queryableString:
        "Beef Stir-Fry 1 lb beef sirloin, thinly sliced 2 tablespoons soy sauce 1 tablespoon oyster sauce 1 tablespoon cornstarch 1 tablespoon vegetable oil 2 cloves garlic, minced 1 bell pepper, sliced 1 onion, sliced 1 cup broccoli florets 1/2 cup sliced mushrooms 1/2 cup beef broth Salt and pepper Cooked rice or noodles",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Chicken Parmesan",
    description:
        "Indulge in this classic Italian dish of tender breaded chicken breasts topped with marinara sauce and melted cheese.",
    illustrationPic: "64890db908b8f19b4dec",
    ingredients: [
      "2 boneless, skinless chicken breasts",
      "1/2 cup all-purpose flour",
      "2 eggs, beaten",
      "1 cup breadcrumbs",
      "1/2 cup grated Parmesan cheese",
      "1 cup marinara sauce",
      "1 cup shredded mozzarella cheese",
      "1/4 cup chopped fresh basil",
      "Salt and pepper to taste",
      "Cooked spaghetti or pasta (for serving)",
    ],
    cookingTime: "30 min",
    cookingSteps: [
      "Preheat the oven to 375°F (190°C).",
      "Place the flour, beaten eggs, and breadcrumbs in three separate shallow bowls.",
      "Season the chicken breasts with salt and pepper.",
      "Dredge each chicken breast in the flour, shaking off any excess.",
      "Dip the floured chicken breast into the beaten eggs, allowing any excess to drip off.",
      "Coat the chicken breast with the breadcrumb mixture, pressing gently to adhere the breadcrumbs to the chicken.",
      "Heat a skillet over medium heat and add a tablespoon of oil. Cook the breaded chicken breasts for 3-4 minutes on each side until golden brown.",
      "Transfer the cooked chicken breasts to a baking dish.",
      "Spread marinara sauce over the chicken breasts.",
      "Sprinkle shredded mozzarella cheese and grated Parmesan cheese over the marinara sauce.",
      "Bake in the preheated oven for 15-20 minutes until the cheese is melted and bubbly.",
      "Garnish with chopped fresh basil and serve the chicken Parmesan over cooked spaghetti or pasta.",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
    ],
    likes: 160,
    views: 130,
    queryableString:
        "Chicken Parmesan 2 boneless, skinless chicken breasts 1/2 cup all-purpose flour 2 eggs, beaten 1 cup breadcrumbs 1/2 cup grated Parmesan cheese 1 cup marinara sauce 1 cup shredded mozzarella cheese 1/4 cup chopped fresh basil Salt and pepper Cooked spaghetti or pasta",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Vegetable Stir-Fry",
    description:
        "Enjoy a colorful and healthy vegetable stir-fry featuring a variety of crisp vegetables tossed in a flavorful sauce.",
    illustrationPic: "64890db908b8f19b4dec",
    ingredients: [
      "2 tablespoons vegetable oil",
      "2 cloves garlic, minced",
      "1 red bell pepper, sliced",
      "1 yellow bell pepper, sliced",
      "1 green bell pepper, sliced",
      "1 cup snow peas",
      "1 cup sliced carrots",
      "1 cup broccoli florets",
      "1 cup sliced mushrooms",
      "1/2 cup sliced onions",
      "2 tablespoons soy sauce",
      "1 tablespoon oyster sauce",
      "1 teaspoon sesame oil",
      "1/2 teaspoon cornstarch",
      "Salt and pepper to taste",
      "Cooked rice or noodles (for serving)",
    ],
    cookingTime: "15 min",
    cookingSteps: [
      "Heat the vegetable oil in a large skillet or wok over high heat.",
      "Add the minced garlic to the skillet and stir-fry for a few seconds until fragrant.",
      "Add the sliced bell peppers, snow peas, carrots, broccoli florets, mushrooms, and onions to the skillet. Stir-fry for 4-5 minutes until the vegetables are crisp-tender.",
      "In a small bowl, whisk together the soy sauce, oyster sauce, sesame oil, cornstarch, salt, and pepper.",
      "Pour the sauce mixture over the vegetables in the skillet. Stir-fry for another minute until the sauce thickens and coats the vegetables.",
      "Remove from heat and serve the vegetable stir-fry over cooked rice or noodles.",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
    ],
    likes: 170,
    views: 140,
    queryableString:
        "Vegetable Stir-Fry 2 tablespoons vegetable oil 2 cloves garlic, minced 1 red bell pepper, sliced 1 yellow bell pepper, sliced 1 green bell pepper, sliced 1 cup snow peas 1 cup sliced carrots 1 cup broccoli florets 1 cup sliced mushrooms 1/2 cup sliced onions 2 tablespoons soy sauce 1 tablespoon oyster sauce 1 teaspoon sesame oil 1/2 teaspoon cornstarch Salt and pepper Cooked rice or noodles",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Pasta Carbonara",
    description:
        "Indulge in a classic Italian pasta dish with creamy egg and cheese sauce, crispy bacon, and al dente spaghetti.",
    illustrationPic: "64890db908b8f19b4dec",
    ingredients: [
      "8 oz spaghetti",
      "4 slices bacon, chopped",
      "2 cloves garlic, minced",
      "2 large eggs",
      "1/2 cup grated Parmesan cheese",
      "1/4 cup chopped fresh parsley",
      "Salt and pepper to taste",
    ],
    cookingTime: "20 min",
    cookingSteps: [
      "Cook the spaghetti according to the package instructions until al dente. Drain and set aside.",
      "In a skillet, cook the chopped bacon over medium heat until crispy. Remove the bacon from the skillet and set aside.",
      "In the same skillet, sauté the minced garlic in the bacon grease until fragrant.",
      "In a bowl, whisk together the eggs, grated Parmesan cheese, chopped fresh parsley, salt, and pepper.",
      "Add the cooked spaghetti to the skillet with the sautéed garlic. Toss to coat the spaghetti with the bacon grease.",
      "Pour the egg mixture over the spaghetti and quickly toss to coat the pasta. The heat from the spaghetti will cook the eggs and create a creamy sauce.",
      "Add the crispy bacon back to the skillet and toss with the pasta.",
      "Serve the pasta carbonara hot, garnished with additional grated Parmesan cheese and chopped parsley.",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
    ],
    likes: 180,
    views: 150,
    queryableString:
        "Pasta Carbonara 8 oz spaghetti 4 slices bacon, chopped 2 cloves garlic, minced 2 large eggs 1/2 cup grated Parmesan cheese 1/4 cup chopped fresh parsley Salt and pepper",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Caprese Salad",
    description:
        "Savor the freshness of a classic Caprese salad with ripe tomatoes, fresh mozzarella cheese, fragrant basil leaves, and a drizzle of balsamic glaze.",
    illustrationPic: "64890db908b8f19b4dec",
    ingredients: [
      "2 large tomatoes, sliced",
      "8 oz fresh mozzarella cheese, sliced",
      "Fresh basil leaves",
      "2 tablespoons balsamic glaze",
      "2 tablespoons extra virgin olive oil",
      "Salt and pepper to taste",
    ],
    cookingTime: "10 min",
    cookingSteps: [
      "Arrange the sliced tomatoes and fresh mozzarella cheese on a serving platter.",
      "Tuck fresh basil leaves between the tomato and mozzarella slices.",
      "Drizzle balsamic glaze and extra virgin olive oil over the salad.",
      "Season with salt and pepper to taste.",
      "Serve the Caprese salad as a refreshing appetizer or side dish.",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      ""
    ],
    likes: 190,
    views: 160,
    queryableString:
        "Caprese Salad 2 large tomatoes, sliced 8 oz fresh mozzarella cheese, sliced Fresh basil leaves 2 tablespoons balsamic glaze 2 tablespoons extra virgin olive oil Salt and pepper",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Shrimp Scampi",
    description:
        "Delight in a flavorful and buttery shrimp scampi dish served with linguine pasta and garnished with fresh parsley.",
    illustrationPic: "64890db908b8f19b4dec",
    ingredients: [
      "8 oz linguine pasta",
      "1 lb large shrimp, peeled and deveined",
      "4 tablespoons butter",
      "4 cloves garlic, minced",
      "1/2 cup white wine",
      "1 tablespoon lemon juice",
      "1/4 teaspoon red pepper flakes",
      "Salt and pepper to taste",
      "Chopped fresh parsley (for garnish)",
    ],
    cookingTime: "15 min",
    cookingSteps: [
      "Cook the linguine pasta according to the package instructions until al dente. Drain and set aside.",
      "In a skillet, melt the butter over medium heat.",
      "Add the minced garlic to the skillet and sauté until fragrant.",
      "Add the peeled and deveined shrimp to the skillet. Cook for 2-3 minutes until the shrimp turn pink and opaque.",
      "Pour the white wine and lemon juice into the skillet. Add the red pepper flakes, salt, and pepper. Stir to combine.",
      "Simmer the shrimp in the sauce for another 2-3 minutes until the flavors meld together.",
      "Remove from heat and toss the cooked linguine pasta with the shrimp scampi sauce.",
      "Garnish with chopped fresh parsley and serve the shrimp scampi hot.",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
    ],
    likes: 200,
    views: 170,
    queryableString:
        "Shrimp Scampi 8 oz linguine pasta 1 lb large shrimp, peeled and deveined 4 tablespoons butter 4 cloves garlic, minced 1/2 cup white wine 1 tablespoon lemon juice 1/4 teaspoon red pepper flakes Salt and pepper Chopped fresh parsley",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Mediterranean Quinoa Salad",
    description:
        "Enjoy a refreshing and nutritious Mediterranean-inspired salad with quinoa, fresh vegetables, feta cheese, and a tangy lemon dressing.",
    illustrationPic: "64890db908b8f19b4dec",
    ingredients: [
      "1 cup cooked quinoa",
      "1 cup cherry tomatoes, halved",
      "1 cucumber, diced",
      "1/2 cup Kalamata olives, pitted and halved",
      "1/4 cup red onion, finely chopped",
      "1/2 cup crumbled feta cheese",
      "2 tablespoons chopped fresh parsley",
      "2 tablespoons extra virgin olive oil",
      "1 tablespoon lemon juice",
      "1 clove garlic, minced",
      "Salt and pepper to taste",
    ],
    cookingTime: "15 min",
    cookingSteps: [
      "In a large bowl, combine the cooked quinoa, cherry tomatoes, cucumber, Kalamata olives, red onion, crumbled feta cheese, and chopped fresh parsley.",
      "In a separate small bowl, whisk together the extra virgin olive oil, lemon juice, minced garlic, salt, and pepper to create the dressing.",
      "Pour the dressing over the quinoa salad and toss to coat the ingredients evenly.",
      "Adjust the seasoning with salt and pepper as desired.",
      "Serve the Mediterranean quinoa salad chilled or at room temperature.",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      ""
    ],
    likes: 210,
    views: 180,
    queryableString:
        "Mediterranean Quinoa Salad 1 cup cooked quinoa 1 cup cherry tomatoes, halved 1 cucumber, diced 1/2 cup Kalamata olives, pitted and halved 1/4 cup red onion, finely chopped 1/2 cup crumbled feta cheese 2 tablespoons chopped fresh parsley 2 tablespoons extra virgin olive oil 1 tablespoon lemon juice 1 clove garlic, minced Salt and pepper",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Teriyaki Salmon",
    description:
        "Savor a delicious and healthy teriyaki-glazed salmon fillet, perfectly seared and served with steamed rice and vegetables.",
    illustrationPic: "64890db908b8f19b4dec",
    ingredients: [
      "2 salmon fillets",
      "1/4 cup soy sauce",
      "2 tablespoons honey",
      "1 tablespoon rice vinegar",
      "1 clove garlic, minced",
      "1 teaspoon grated ginger",
      "1 tablespoon vegetable oil",
      "Steamed rice (for serving)",
      "Steamed vegetables (for serving)",
      "Sesame seeds (for garnish)",
      "Sliced green onions (for garnish)",
    ],
    cookingTime: "20 min",
    cookingSteps: [
      "In a small bowl, whisk together the soy sauce, honey, rice vinegar, minced garlic, and grated ginger to create the teriyaki sauce.",
      "Heat the vegetable oil in a skillet over medium-high heat.",
      "Place the salmon fillets skin-side down in the hot skillet. Cook for 3-4 minutes until the skin is crispy.",
      "Flip the salmon fillets and pour the teriyaki sauce over them. Cook for another 3-4 minutes until the salmon is cooked through and the sauce has thickened.",
      "Remove from heat and serve the teriyaki salmon over steamed rice and vegetables.",
      "Garnish with sesame seeds and sliced green onions.",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      ""
    ],
    likes: 220,
    views: 190,
    queryableString:
        "Teriyaki Salmon 2 salmon fillets 1/4 cup soy sauce 2 tablespoons honey 1 tablespoon rice vinegar 1 clove garlic, minced 1 teaspoon grated ginger 1 tablespoon vegetable oil Steamed rice Steamed vegetables Sesame seeds Sliced green onions",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Greek Gyro",
    description:
        "Experience the flavors of Greece with a homemade gyro filled with succulent grilled meat, tzatziki sauce, fresh vegetables, and warm pita bread.",
    illustrationPic: "64890db908b8f19b4dec",
    ingredients: [
      "1 lb lamb or chicken, thinly sliced",
      "1/4 cup olive oil",
      "2 tablespoons lemon juice",
      "2 cloves garlic, minced",
      "1 teaspoon dried oregano",
      "Salt and pepper to taste",
      "Tzatziki sauce",
      "Sliced tomatoes",
      "Sliced cucumbers",
      "Sliced red onions",
      "Warm pita bread",
    ],
    cookingTime: "30 min",
    cookingSteps: [
      "In a bowl, combine the olive oil, lemon juice, minced garlic, dried oregano, salt, and pepper to create the marinade.",
      "Add the thinly sliced lamb or chicken to the marinade. Toss to coat the meat evenly. Let it marinate for at least 20 minutes.",
      "Heat a grill or skillet over medium-high heat.",
      "Cook the marinated meat for 3-4 minutes per side until cooked through and slightly charred.",
      "Remove from heat and let the meat rest for a few minutes. Slice into thin strips.",
      "Warm the pita bread on the grill or in a toaster.",
      "Spread tzatziki sauce on the warmed pita bread. Top with the sliced meat, tomatoes, cucumbers, and red onions.",
      "Roll up the gyro and secure it with foil or a toothpick.",
      "Serve the Greek gyro warm and enjoy!",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      ""
    ],
    likes: 230,
    views: 200,
    queryableString:
        "Greek Gyro 1 lb lamb or chicken, thinly sliced 1/4 cup olive oil 2 tablespoons lemon juice 2 cloves garlic, minced 1 teaspoon dried oregano Salt and pepper Tzatziki sauce Sliced tomatoes Sliced cucumbers Sliced red onions Warm pita bread",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Chicken Parmesan",
    description:
        "Indulge in a classic Italian favorite with tender breaded chicken cutlets, savory marinara sauce, melted mozzarella cheese, and spaghetti.",
    illustrationPic: "64890db908b8f19b4dec",
    ingredients: [
      "2 boneless, skinless chicken breasts",
      "1/2 cup breadcrumbs",
      "1/4 cup grated Parmesan cheese",
      "1 teaspoon dried basil",
      "1 teaspoon dried oregano",
      "Salt and pepper to taste",
      "1 cup marinara sauce",
      "1/2 cup shredded mozzarella cheese",
      "Cooked spaghetti (for serving)",
      "Chopped fresh parsley (for garnish)",
    ],
    cookingTime: "35 min",
    cookingSteps: [
      "Preheat the oven to 400°F (200°C).",
      "In a shallow bowl, combine the breadcrumbs, grated Parmesan cheese, dried basil, dried oregano, salt, and pepper.",
      "Dip each chicken breast into the breadcrumb mixture, pressing gently to adhere the breadcrumbs to the chicken.",
      "Place the breaded chicken breasts on a baking sheet lined with parchment paper.",
      "Bake in the preheated oven for 20-25 minutes until the chicken is cooked through and the breadcrumbs are golden and crispy.",
      "Remove the chicken from the oven and spoon marinara sauce over each chicken breast. Top with shredded mozzarella cheese.",
      "Return the chicken to the oven and bake for another 5-10 minutes until the cheese is melted and bubbly.",
      "While the chicken is baking, cook spaghetti according to the package instructions until al dente. Drain.",
      "Serve the chicken Parmesan over cooked spaghetti, garnished with chopped fresh parsley.",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      ""
    ],
    likes: 240,
    views: 210,
    queryableString:
        "Chicken Parmesan 2 boneless, skinless chicken breasts 1/2 cup breadcrumbs 1/4 cup grated Parmesan cheese 1 teaspoon dried basil 1 teaspoon dried oregano Salt and pepper 1 cup marinara sauce 1/2 cup shredded mozzarella cheese Cooked spaghetti Chopped fresh parsley",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Vegetable Curry",
    description:
        "Delight in a flavorful and aromatic vegetable curry packed with a medley of colorful vegetables, fragrant spices, and creamy coconut milk.",
    illustrationPic: "64890db908b8f19b4dec",
    ingredients: [
      "1 tablespoon vegetable oil",
      "1 onion, diced",
      "2 cloves garlic, minced",
      "1 tablespoon grated ginger",
      "2 tablespoons curry powder",
      "1 teaspoon turmeric",
      "1 teaspoon cumin",
      "1 teaspoon paprika",
      "1 can (14 oz) coconut milk",
      "2 cups mixed vegetables (e.g., carrots, bell peppers, broccoli, peas)",
      "Salt and pepper to taste",
      "Cooked rice (for serving)",
      "Chopped fresh cilantro (for garnish)",
    ],
    cookingTime: "25 min",
    cookingSteps: [
      "Heat the vegetable oil in a large skillet or pot over medium heat.",
      "Add the diced onion, minced garlic, and grated ginger to the skillet. Sauté until the onion becomes translucent and fragrant.",
      "Stir in the curry powder, turmeric, cumin, and paprika. Cook for another minute to toast the spices.",
      "Pour in the coconut milk and stir to combine with the spices.",
      "Add the mixed vegetables to the skillet. Stir to coat the vegetables with the curry sauce.",
      "Cover the skillet and simmer for 15-20 minutes until the vegetables are tender.",
      "Season the vegetable curry with salt and pepper to taste.",
      "Serve the vegetable curry over cooked rice, garnished with chopped fresh cilantro.",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
    ],
    likes: 250,
    views: 220,
    queryableString:
        "Vegetable Curry 1 tablespoon vegetable oil 1 onion, diced 2 cloves garlic, minced 1 tablespoon grated ginger 2 tablespoons curry powder 1 teaspoon turmeric 1 teaspoon cumin 1 teaspoon paprika 1 can (14 oz) coconut milk 2 cups mixed vegetables Salt and pepper Cooked rice Chopped fresh cilantro",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Beef Stir-Fry",
    description:
        "Satisfy your cravings with a quick and flavorful beef stir-fry, featuring tender beef slices, crisp vegetables, and a savory soy-based sauce.",
    illustrationPic: "64890db908b8f19b4dec",
    ingredients: [
      "1 lb beef sirloin, thinly sliced",
      "2 tablespoons soy sauce",
      "2 tablespoons oyster sauce",
      "1 tablespoon hoisin sauce",
      "1 tablespoon cornstarch",
      "1 tablespoon vegetable oil",
      "1 onion, sliced",
      "1 bell pepper, sliced",
      "1 cup broccoli florets",
      "1 cup snap peas",
      "2 cloves garlic, minced",
      "1 teaspoon grated ginger",
      "Salt and pepper to taste",
      "Cooked rice or noodles (for serving)",
    ],
    cookingTime: "20 min",
    cookingSteps: [
      "In a bowl, combine the soy sauce, oyster sauce, hoisin sauce, and cornstarch. Stir until the cornstarch is dissolved and the sauce is well mixed.",
      "Heat the vegetable oil in a large skillet or wok over high heat.",
      "Add the thinly sliced beef to the skillet. Stir-fry for 2-3 minutes until the beef is browned and cooked to your desired level of doneness. Remove the beef from the skillet and set aside.",
      "In the same skillet, add the sliced onion, bell pepper, broccoli florets, snap peas, minced garlic, and grated ginger. Stir-fry for 3-4 minutes until the vegetables are crisp-tender.",
      "Return the cooked beef to the skillet. Pour the sauce over the beef and vegetables. Stir-fry for another minute until the sauce thickens and coats the ingredients.",
      "Season with salt and pepper to taste.",
      "Serve the beef stir-fry over cooked rice or noodles.",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
    ],
    likes: 260,
    views: 230,
    queryableString:
        "Beef Stir-Fry 1 lb beef sirloin, thinly sliced 2 tablespoons soy sauce 2 tablespoons oyster sauce 1 tablespoon hoisin sauce 1 tablespoon cornstarch 1 tablespoon vegetable oil 1 onion, sliced 1 bell pepper, sliced 1 cup broccoli florets 1 cup snap peas 2 cloves garlic, minced 1 teaspoon grated ginger Salt and pepper Cooked rice or noodles",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Caprese Salad",
    description:
        "Enjoy a light and refreshing Caprese salad featuring ripe tomatoes, fresh mozzarella cheese, fragrant basil leaves, and a drizzle of balsamic glaze.",
    illustrationPic: "64890db908b8f19b4dec",
    ingredients: [
      "2 large tomatoes, sliced",
      "8 oz fresh mozzarella cheese, sliced",
      "Handful of fresh basil leaves",
      "2 tablespoons extra virgin olive oil",
      "2 tablespoons balsamic glaze",
      "Salt and pepper to taste",
    ],
    cookingTime: "10 min",
    cookingSteps: [
      "Arrange the sliced tomatoes and fresh mozzarella cheese on a serving platter, alternating them in a single layer.",
      "Tuck the fresh basil leaves between the tomato and mozzarella slices.",
      "Drizzle the extra virgin olive oil over the salad.",
      "Drizzle the balsamic glaze over the salad in a zigzag pattern.",
      "Season with salt and pepper to taste.",
      "Serve the Caprese salad immediately and enjoy!",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
    ],
    likes: 270,
    views: 240,
    queryableString:
        "Caprese Salad 2 large tomatoes, sliced 8 oz fresh mozzarella cheese, sliced Handful of fresh basil leaves 2 tablespoons extra virgin olive oil 2 tablespoons balsamic glaze Salt and pepper",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Homemade Pizza",
    description:
        "Create your own delicious homemade pizza with a crispy crust, tangy tomato sauce, melty cheese, and your favorite toppings.",
    illustrationPic: "64890db908b8f19b4dec",
    ingredients: [
      "Pizza dough",
      "Tomato sauce",
      "Shredded mozzarella cheese",
      "Toppings of your choice (e.g., pepperoni, sliced bell peppers, mushrooms, onions)",
      "Fresh basil leaves",
      "Salt and pepper to taste",
      "Cornmeal (for dusting)",
    ],
    cookingTime: "25 min",
    cookingSteps: [
      "Preheat the oven to the temperature recommended on the pizza dough package.",
      "Roll out the pizza dough on a floured surface to your desired thickness.",
      "Transfer the rolled-out dough to a baking sheet or pizza stone that has been lightly dusted with cornmeal.",
      "Spread a layer of tomato sauce evenly over the pizza dough, leaving a border around the edges for the crust.",
      "Sprinkle shredded mozzarella cheese over the sauce.",
      "Add your desired toppings, such as pepperoni, sliced bell peppers, mushrooms, and onions.",
      "Season with salt and pepper to taste.",
      "Bake the pizza in the preheated oven for the time specified on the pizza dough package, or until the crust is golden and the cheese is bubbly and slightly browned.",
      "Remove the pizza from the oven and let it cool for a few minutes.",
      "Garnish with fresh basil leaves before serving.",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
    ],
    likes: 280,
    views: 250,
    queryableString:
        "Homemade Pizza Pizza dough Tomato sauce Shredded mozzarella cheese Toppings Fresh basil leaves Salt and pepper Cornmeal",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Mango Salsa",
    description:
        "Add a tropical twist to your meals with a refreshing mango salsa, featuring ripe mangoes, tangy lime juice, spicy jalapenos, and fresh cilantro.",
    illustrationPic: "64890db908b8f19b4dec",
    ingredients: [
      "2 ripe mangoes, diced",
      "1/2 red onion, finely chopped",
      "1 jalapeno pepper, seeded and minced",
      "Handful of fresh cilantro, chopped",
      "Juice of 1 lime",
      "Salt and pepper to taste",
    ],
    cookingTime: "15 min",
    cookingSteps: [
      "In a bowl, combine the diced mangoes, finely chopped red onion, minced jalapeno pepper, and chopped fresh cilantro.",
      "Squeeze the juice of 1 lime over the salsa.",
      "Season with salt and pepper to taste.",
      "Stir the ingredients together until well combined.",
      "Let the mango salsa sit for 10 minutes to allow the flavors to meld together.",
      "Serve the mango salsa as a dip with tortilla chips or as a topping for grilled meats, fish, or tacos.",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      ""
    ],
    likes: 290,
    views: 260,
    queryableString:
        "Mango Salsa 2 ripe mangoes, diced 1/2 red onion, finely chopped 1 jalapeno pepper, minced Handful of fresh cilantro, chopped Juice of 1 lime Salt and pepper",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Chicken Caesar Salad",
    description:
        "Enjoy a classic Chicken Caesar Salad with crisp romaine lettuce, grilled chicken breast, Parmesan cheese, crunchy croutons, and tangy Caesar dressing.",
    illustrationPic: "64890db908b8f19b4dec",
    ingredients: [
      "2 boneless, skinless chicken breasts",
      "Salt and pepper to taste",
      "1 tablespoon olive oil",
      "1 head romaine lettuce, chopped",
      "1/2 cup Caesar dressing",
      "1/4 cup grated Parmesan cheese",
      "1 cup croutons",
    ],
    cookingTime: "25 min",
    cookingSteps: [
      "Season the chicken breasts with salt and pepper to taste.",
      "Heat the olive oil in a skillet over medium-high heat.",
      "Add the chicken breasts to the skillet and cook for 6-8 minutes per side, or until cooked through and no longer pink in the center.",
      "Remove the chicken from the skillet and let it rest for a few minutes. Then, slice the chicken into thin strips.",
      "In a large bowl, combine the chopped romaine lettuce, Caesar dressing, grated Parmesan cheese, and croutons. Toss to coat the lettuce evenly with the dressing.",
      "Divide the Caesar salad mixture onto individual plates or bowls.",
      "Top each plate of salad with the sliced grilled chicken.",
      "Serve the Chicken Caesar Salad immediately and enjoy!",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
    ],
    likes: 300,
    views: 270,
    queryableString:
        "Chicken Caesar Salad 2 boneless, skinless chicken breasts Salt and pepper 1 tablespoon olive oil 1 head romaine lettuce, chopped 1/2 cup Caesar dressing 1/4 cup grated Parmesan cheese 1 cup croutons",
  ),
  RecipeModel(
    id: ID.unique(),
    userName: 'No Name Dev',
    uid: "646894e6efbdf9f5961e",
    title: "( Demo ) Chocolate Chip Cookies",
    description:
        "Satisfy your sweet tooth with homemade chocolate chip cookies featuring a soft and chewy texture, gooey chocolate chips, and a hint of vanilla.",
    illustrationPic: "64890db908b8f19b4dec",
    ingredients: [
      "1 cup unsalted butter, softened",
      "1 cup granulated sugar",
      "1 cup packed brown sugar",
      "2 large eggs",
      "1 teaspoon vanilla extract",
      "3 cups all-purpose flour",
      "1 teaspoon baking soda",
      "1/2 teaspoon salt",
      "2 cups chocolate chips",
    ],
    cookingTime: "15 min",
    cookingSteps: [
      "Preheat the oven to 350°F (175°C).",
      "In a large bowl, cream together the softened butter, granulated sugar, and brown sugar until light and fluffy.",
      "Beat in the eggs one at a time, then stir in the vanilla extract.",
      "In a separate bowl, combine the all-purpose flour, baking soda, and salt.",
      "Gradually add the dry ingredients to the butter mixture, mixing well after each addition.",
      "Fold in the chocolate chips.",
      "Drop rounded tablespoonfuls of dough onto ungreased baking sheets.",
      "Bake in the preheated oven for 10-12 minutes, or until golden brown around the edges.",
      "Allow the cookies to cool on the baking sheets for 5 minutes before transferring them to wire racks to cool completely.",
    ],
    cookingStepsPics: [
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      "64890df3395826a7def0",
      ""
    ],
    likes: 310,
    views: 280,
    queryableString:
        "Chocolate Chip Cookies 1 cup unsalted butter, softened 1 cup granulated sugar 1 cup packed brown sugar 2 large eggs 1 teaspoon vanilla extract 3 cups all-purpose flour 1 teaspoon baking soda 1/2 teaspoon salt 2 cups chocolate chips",
  ),
];
